# Site settings
title: HD4630 workshops
description: "Workshop materials for Cornell HD4630: Introduction to Functional MRI analysis."
url: "emdupre.github.io/hd4630_workshops"

author:
  name: "Elizabeth DuPre"
  twitter_username: emdupre_
  github_username:  emdupre

# Build settings
baseurl: '/hd4630_workshops' # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate


# Options
custom_header: false
custom_nav_footer: false
reverse: false
